# Generated by Django 5.2.6 on 2025-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tabelle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paxtonviewweb',
            options={'managed': False, 'ordering': ['createtime', 'kartennummer'], 'verbose_name': 'Mitarbeiten_Tabelle', 'verbose_name_plural': 'Mitarbeiten_Tabelle'},
        ),
        migrations.AlterModelOptions(
            name='tgast',
            options={'managed': False, 'ordering': ['createtime', 'kartennummer'], 'verbose_name': 'Gäste_Tabelle', 'verbose_name_plural': 'Gäste_Tabelle'},
        ),
        migrations.AlterModelOptions(
            name='tstudenten',
            options={'managed': False, 'ordering': ['createtime', 'kartennummer'], 'verbose_name': 'Studenten_Tabelle', 'verbose_name_plural': 'Studenten_Tabelle'},
        ),
    ]
